apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-alibaba-oss
spec:
  components:
    - name: alibaba-oss
      type: alibaba-oss
      properties:
        bucket: vela-website-20220323-1928
        acl: private
        writeConnectionSecretToRef:
          name: oss-conn