apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-alibaba-redis
spec:
  components:
    - name: sample-redis
      type: alibaba-redis
      properties:
        instance_name: oam-redis
        account_name: oam
        password: Xyfff83jfewGGfaked
        writeConnectionSecretToRef:
          name: redis-conn