apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-alibaba-rds-multiple-databases
spec:
  components:
    - name: db
      type: alibaba-rds
      properties:
        instance_name: dblinks
        account_name: oamtest
        password: U34rfwefwefffaked
        databases:
          - name: dev
            character_set: utf8
            description: "dev database"
          - name: prod
            character_set: utf8
            description: "prod database"
        writeConnectionSecretToRef:
          name: db-conn
