apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-alibaba-ask
spec:
  components:
    - name: sample-ask
      type: alibaba-ask
      properties:
        name: kubevela

        writeConnectionSecretToRef:
          name: ask-conn