apiVersion: core.oam.dev/v1beta2
kind: Application
metadata:
  name: anoop-emr
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  components:
    - name: anoop-emr-tf-component
      type: aws-emr
      properties:
        name: "anoop-emr-tf-component"
        region: "us-east-2"
        vpc_id: "xxxx"
        subnet_id: "xxxxxx"
        applications:
          - "Spark"
        core_instance_group_instance_type: "m4.large"
        core_instance_group_ebs_size: 1
        master_instance_group_instance_type: "m4.large"
        master_instance_group_ebs_size: 1
        writeConnectionSecretToRef:
          name: anoop-emr-details
          namespace: default
