apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-azure-subnet
spec:
  components:
    - name: mariadb-backend
      type: azure-subnet
      properties:
        name: "dev"
        address_space: "10.0.0.0/16"
        writeConnectionSecretToRef:
          name: azure-subnet-conn
          namespace: vela-system